### ISSUE TITLE
[epic] Implementing shaped proposal 202401: Presenting our Strategy

### ISSUE THREAD

**Issue by elisapaka** [life-itself/strategy#1]
An issue for implementing the shaped proposal "[Presenting our Strategy](https://github.com/life-itself/comms/blob/main/shaping/202401%20Presenting%20our%20Strategy%20v3%20in%20its%20current%20form.md)". 

## Summary of shaped proposal

- Appetite: 3d (reduced by 1d given we spent 1.5d in shaping and work we did in shaping will help)
- Problem: lot of strategy-related materials but they aren't woven together or consolidated which creates a sense of overwhelm and confusion and prevents them being published and used.
- Solution: inventory materials, create framework to organize them, create roadmap for publication. If we can, start on consolidated strategy.

## Acceptance

- [ ] A complete inventory of existing materials related to Life Itself strategy (V2 and V3) in the strategy repo
- [ ] A framework for organising materials 
- [ ] Most important materials are organised according to the framework in a visual map or similar
- [ ] A roadmap for publishing the consolidated strategy (e.g. in the form of a DAG of recommended outputs with estimates)
- [ ] Bonus: Sketch of long-form consolidated v3 strategy
- [ ] Bonus: Consolidated v2 strategy

## Tasks

- [ ] Complete the inventory of strategy materials in the Strategy repo
  - [ ] Add all materials in the excalidraw (https://app.excalidraw.com/l/9u8crB2ZmUo/3EkbCxN8qBi) to the `strategy/materials` vault
  - [ ] Create Dataview layout
  - [ ] After 5-10 entries, assess if we want to add metadata
- [ ] Develop framework for organising the most important materials
- [ ] Organise materials in inventory according to the framework
- [ ] Create a roadmap for publishing the consolidated strategy

**Comment by elisapaka** [comment]
@rufuspollock I've sketched out a suggestion for what frontmatter properties to include here: https://github.com/life-itself/strategy/blob/main/Framework.md. Let me know your thoughts / feel free to edit directly. 

Other updates: added several materials and renamed the images.

**Comment by elisapaka** [comment]
@rufuspollock I've added all the strategy materials that we had on the excalidraw. See here: https://github.com/life-itself/strategy/tree/main/materials

I saw that you've added one material called "Multiple why levels issue 36 Sep 2021". It has no url or any other identifying information, so I haven't done anything with that.

I also saw you added "Oct 2021 Consolidated List of Materials" - I've yet to go through this list.
